version: '3.8'

services:
  gocontas-back-end: 
    image: bitnami/postgresql
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=gocontas-backend